#YOUR NAME AND YOUR PARTNER'S NAME GOES HERE
#THE NAME OF THE ALGORITHM GOES HERE

#CLASSES GO HERE


if __name__ == '__main__':
#REMOVE PASS AND DEMONSTRATE THE SCHEDULER IN ACTION HERE
#CREATE ANY QUEUES, PROCESSES, CALL APPROPRIATE METHODS
    pass